### ISSUE TITLE
Add CLI option to filter CWE IDs

### ISSUE THREAD

**Issue by Sim4n6** [projectdiscovery/cvemap#48]
CLI option to filter CVEs for given CWE ID.

```
   -cwe, -cwe-id string[]       cve to list for given cwe id
```

Example:

```
cvemap -l 30 -cwe 416
```

**Comment by parthmalhotra** [comment]
@Sim4n6 : Here is the command for it `cvemap -l 30 -s "critical" -f "cwe" -q 'weaknesses.$.cwe_id:CWE-416'`

<img width="1017" alt="image" src="https://github.com/projectdiscovery/cvemap/assets/28601533/c040508c-bcfb-4aa9-a4df-ffbe03e89d5c">

**Comment by Sim4n6** [comment]
perfect !
