### ISSUE TITLE
Authentication on headless setups

### ISSUE THREAD

**Issue by jivarson** [projectdiscovery/cvemap#51]
Would be nice if API-token could be provided as argument to "cvemap -auth". Would simplify headless or unattended scenarios.

**Comment by jivarson** [comment]
would be nice if auth token could be provided as argument instead/as well

**Comment by Co5mos** [comment]
Does use an environment variable like `export PDCP_API_KEY=xxx` satisfy your needs?

**Comment by jivarson** [comment]
I'm actually using the Windows binary. but can only run non-interactive scripts remotely.
Can probably set a environment variable, but it would be way easier with `cvemap -auth <token>`

**Comment by RamanaReddy0M** [comment]
> Does use an environment variable like `export PDCP_API_KEY=xxx` satisfy your needs?

@Co5mos Yes, this also lets you use cvemap without 401 error.

**Comment by jivarson** [comment]
I was able to utilize psexec to get into the right securitycontext interactively, closing this, but the environment variable didnt seem to work for Windows anyhow
